language: java
jdk:
 - oraclejdk8
script:
  - mvn install
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file: "target/Installer*.jar"
  file_glob: true
  skip_cleanup: true
  on:
    branch: master
after_success:
  - ls target/
  - echo "target/Installer*.jar"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_JOB_ID-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push origin $GIT_TAG
